export interface ChapterVerse {
  number: number;
  text: string;
  keywords: string[];
}

export interface Chapter {
  slug: string;
  book: string;
  chapter: number;
  reference: string;
  verses: ChapterVerse[];
}

// NASB text supplied by the user. Single round of fill-in-the-blank: only the
// listed key words are blanked. Generated by scripts/build-chapters.mjs.
export const chapters: Chapter[] = [
  {
    slug: "philippians-1",
    book: "Philippians",
    chapter: 1,
    reference: "Philippians 1",
    verses: [
      {
        number: 1,
        text: "Paul and Timothy, bond-servants of Christ Jesus, To all the saints in Christ Jesus who are in Philippi, including the overseers and deacons:",
        keywords: ["Christ", "Jesus", "Timothy"],
      },
      {
        number: 2,
        text: "Grace to you and peace from God our Father and the Lord Jesus Christ.",
        keywords: ["Grace", "Father"],
      },
      {
        number: 3,
        text: "I thank my God in all my remembrance of you,",
        keywords: ["God"],
      },
      {
        number: 4,
        text: "always offering prayer with joy in my every prayer for you all,",
        keywords: ["offering"],
      },
      {
        number: 5,
        text: "in view of your participation in the gospel from the first day until now.",
        keywords: ["gospel", "participation"],
      },
      {
        number: 6,
        text: "For I am confident of this very thing, that He who began a good work among you will complete it by the day of Christ Jesus.",
        keywords: ["Christ", "Jesus", "confident"],
      },
      {
        number: 7,
        text: "For it is only right for me to feel this way about you all, because I have you in my heart, since both in my imprisonment and in the defense and confirmation of the gospel, you all are partakers of grace with me.",
        keywords: ["gospel", "grace", "imprisonment"],
      },
      {
        number: 8,
        text: "For God is my witness, how I long for you all with the affection of Christ Jesus.",
        keywords: ["Christ", "Jesus"],
      },
      {
        number: 9,
        text: "And this I pray, that your love may overflow still more and more in real knowledge and all discernment,",
        keywords: ["love", "overflow"],
      },
      {
        number: 10,
        text: "so that you may discover the things that are excellent, that you may be sincere and blameless for the day of Christ;",
        keywords: ["Christ", "discover"],
      },
      {
        number: 11,
        text: "having been filled with the fruit of righteousness which comes through Jesus Christ, for the glory and praise of God.",
        keywords: ["Jesus", "Christ", "righteousness"],
      },
      {
        number: 12,
        text: "Now I want you to know, brothers and sisters, that my circumstances have turned out for the greater progress of the gospel,",
        keywords: ["gospel", "brothers", "sisters"],
      },
      {
        number: 13,
        text: "so that my imprisonment in the cause of Christ has become well known throughout the praetorian guard and to everyone else,",
        keywords: ["Christ", "imprisonment", "throughout"],
      },
      {
        number: 14,
        text: "and that most of the brothers and sisters, trusting in the Lord because of my imprisonment, have far more courage to speak the word of God without fear.",
        keywords: ["Lord", "God", "brothers"],
      },
      {
        number: 15,
        text: "Some, to be sure, are preaching Christ even from envy and strife, but some also from goodwill;",
        keywords: ["Christ", "preaching"],
      },
      {
        number: 16,
        text: "the latter do it out of love, knowing that I am appointed for the defense of the gospel;",
        keywords: ["gospel", "love"],
      },
      {
        number: 17,
        text: "the former proclaim Christ out of selfish ambition rather than from pure motives, thinking that they are causing me distress in my imprisonment.",
        keywords: ["Christ", "proclaim", "selfish"],
      },
      {
        number: 18,
        text: "What then? Only that in every way, whether in pretense or in truth, Christ is proclaimed, and in this I rejoice. But not only that, I also will rejoice,",
        keywords: ["Christ", "whether"],
      },
      {
        number: 19,
        text: "for I know that this will turn out for my deliverance through your prayers and the provision of the Spirit of Jesus Christ,",
        keywords: ["Spirit", "Jesus"],
      },
      {
        number: 20,
        text: "according to my eager expectation and hope, that I will not be put to shame in anything, but that with all boldness, Christ will even now, as always, be exalted in my body, whether by life or by death.",
        keywords: ["Christ", "death", "hope", "life"],
      },
      {
        number: 21,
        text: "For to me, to live is Christ, and to die is gain.",
        keywords: ["Christ"],
      },
      {
        number: 22,
        text: "But if I am to live on in the flesh, this will mean fruitful labor for me; and I do not know which to choose.",
        keywords: ["fruitful", "flesh"],
      },
      {
        number: 23,
        text: "But I am hard-pressed from both directions, having the desire to depart and be with Christ, for that is very much better;",
        keywords: ["Christ", "hardpressed"],
      },
      {
        number: 24,
        text: "yet to remain on in the flesh is more necessary for your sakes.",
        keywords: ["necessary"],
      },
      {
        number: 25,
        text: "Convinced of this, I know that I will remain and continue with you all for your progress and joy in the faith,",
        keywords: ["faith", "Convinced"],
      },
      {
        number: 26,
        text: "so that your pride in Christ Jesus may be abundant because of me by my coming to you again.",
        keywords: ["Christ", "Jesus"],
      },
      {
        number: 27,
        text: "Only conduct yourselves in a manner worthy of the gospel of Christ, so that whether I come and see you or remain absent, I will hear about you that you are standing firm in one spirit, with one mind striving together for the faith of the gospel;",
        keywords: ["Christ", "gospel", "spirit", "faith", "conduct"],
      },
      {
        number: 28,
        text: "and in no way alarmed by your opponents—which is a sign of destruction for them, but of salvation for you, and this too, from God.",
        keywords: ["salvation", "God"],
      },
      {
        number: 29,
        text: "For to you it has been granted for Christ’s sake, not only to believe in Him, but also to suffer on His behalf,",
        keywords: ["Christs", "granted"],
      },
      {
        number: 30,
        text: "experiencing the same conflict which you saw in me, and now hear to be in me.",
        keywords: ["experiencing"],
      },
    ],
  },
  {
    slug: "philippians-2",
    book: "Philippians",
    chapter: 2,
    reference: "Philippians 2",
    verses: [
      {
        number: 1,
        text: "Therefore if there is any encouragement in Christ, if any consolation of love, if any fellowship of the Spirit, if any affection and compassion,",
        keywords: ["Christ", "Spirit"],
      },
      {
        number: 2,
        text: "make my joy complete by being of the same mind, maintaining the same love, united in spirit, intent on one purpose.",
        keywords: ["spirit", "love", "complete"],
      },
      {
        number: 3,
        text: "Do nothing from selfishness or empty conceit, but with humility consider one another as more important than yourselves;",
        keywords: ["nothing", "selfishness"],
      },
      {
        number: 4,
        text: "do not merely look out for your own personal interests, but also for the interests of others.",
        keywords: ["personal", "interests"],
      },
      {
        number: 5,
        text: "Have this attitude in yourselves which was also in Christ Jesus,",
        keywords: ["Christ"],
      },
      {
        number: 6,
        text: "who, as He already existed in the form of God, did not consider equality with God something to be grasped,",
        keywords: ["God", "already", "existed"],
      },
      {
        number: 7,
        text: "but emptied Himself by taking the form of a bond-servant and being born in the likeness of men.",
        keywords: ["emptied", "bondservant"],
      },
      {
        number: 8,
        text: "And being found in appearance as a man, He humbled Himself by becoming obedient to the point of death: death on a cross.",
        keywords: ["death", "cross", "appearance"],
      },
      {
        number: 9,
        text: "For this reason also God highly exalted Him, and bestowed on Him the name which is above every name,",
        keywords: ["God", "exalted"],
      },
      {
        number: 10,
        text: "so that at the name of Jesus every knee will bow, of those who are in heaven and on earth and under the earth,",
        keywords: ["Jesus", "heaven"],
      },
      {
        number: 11,
        text: "and that every tongue will confess that Jesus Christ is Lord, to the glory of God the Father.",
        keywords: ["Jesus", "Christ"],
      },
      {
        number: 12,
        text: "So then, my beloved, just as you have always obeyed, not as in my presence only, but now much more in my absence, work out your own salvation with fear and trembling;",
        keywords: ["salvation", "beloved", "presence"],
      },
      {
        number: 13,
        text: "for it is God who is at work in you, both to desire and to work for His good pleasure.",
        keywords: ["God", "pleasure"],
      },
      {
        number: 14,
        text: "Do all things without complaining or arguments;",
        keywords: ["without"],
      },
      {
        number: 15,
        text: "so that you will prove yourselves to be blameless and innocent, children of God above reproach in the midst of a crooked and perverse generation, among whom you appear as lights in the world,",
        keywords: ["God", "blameless", "innocent", "children"],
      },
      {
        number: 16,
        text: "holding firmly the word of life, so that on the day of Christ I can take pride because I did not run in vain nor labor in vain.",
        keywords: ["Christ", "life", "holding"],
      },
      {
        number: 17,
        text: "But even if I am being poured out as a drink offering upon the sacrifice and service of your faith, I rejoice and share my joy with you all.",
        keywords: ["faith", "offering", "sacrifice"],
      },
      {
        number: 18,
        text: "You too, I urge you, rejoice in the same way and share your joy with me.",
        keywords: ["rejoice", "share"],
      },
      {
        number: 19,
        text: "But I hope, in the Lord Jesus, to send Timothy to you shortly, so that I also may be encouraged when I learn of your condition.",
        keywords: ["Jesus", "Lord", "hope"],
      },
      {
        number: 20,
        text: "For I have no one else of kindred spirit who will genuinely be concerned for your welfare.",
        keywords: ["spirit", "kindred"],
      },
      {
        number: 21,
        text: "For they all seek after their own interests, not those of Christ Jesus.",
        keywords: ["Christ", "Jesus"],
      },
      {
        number: 22,
        text: "But you know of his proven character, that he served with me in the furtherance of the gospel like a child serving his father.",
        keywords: ["gospel", "father", "character"],
      },
      {
        number: 23,
        text: "Therefore I hope to send him immediately, as soon as I see how things go with me;",
        keywords: ["hope", "immediately"],
      },
      {
        number: 24,
        text: "and I trust in the Lord that I myself will also be coming shortly.",
        keywords: ["Lord"],
      },
      {
        number: 25,
        text: "But I thought it necessary to send to you Epaphroditus, my brother and fellow worker and fellow soldier, who is also your messenger and minister to my need,",
        keywords: ["Epaphroditus", "thought", "necessary"],
      },
      {
        number: 26,
        text: "because he was longing for you all and was distressed because you had heard that he was sick.",
        keywords: ["longing"],
      },
      {
        number: 27,
        text: "For indeed he was sick to the point of death, but God had mercy on him, and not only on him but also on me, so that I would not have sorrow upon sorrow.",
        keywords: ["God", "death"],
      },
      {
        number: 28,
        text: "Therefore I have sent him all the more eagerly, so that when you see him again you may rejoice and I may be less concerned about you.",
        keywords: ["eagerly", "rejoice"],
      },
      {
        number: 29,
        text: "Receive him then in the Lord with all joy, and hold people like him in high regard,",
        keywords: ["Lord", "Receive"],
      },
      {
        number: 30,
        text: "because he came close to death for the work of Christ, risking his life to compensate for your absence in your service to me.",
        keywords: ["Christ", "death", "life"],
      },
    ],
  },
  {
    slug: "philippians-3",
    book: "Philippians",
    chapter: 3,
    reference: "Philippians 3",
    verses: [
      {
        number: 1,
        text: "Finally, my brothers and sisters, rejoice in the Lord. To write the same things again is no trouble for me, and it is a safeguard for you.",
        keywords: ["Lord", "Finally", "brothers"],
      },
      {
        number: 2,
        text: "Beware of the dogs, beware of the evil workers, beware of the false circumcision;",
        keywords: ["Beware", "workers"],
      },
      {
        number: 3,
        text: "for we are the true circumcision, who worship in the Spirit of God and take pride in Christ Jesus, and put no confidence in the flesh,",
        keywords: ["Spirit", "Christ", "Jesus"],
      },
      {
        number: 4,
        text: "although I myself could boast as having confidence even in the flesh. If anyone else thinks he is confident in the flesh, I have more reason:",
        keywords: ["confidence", "confident", "boast"],
      },
      {
        number: 5,
        text: "circumcised the eighth day, of the nation of Israel, of the tribe of Benjamin, a Hebrew of Hebrews; as to the Law, a Pharisee;",
        keywords: ["Benjamin", "Hebrews", "Pharisee"],
      },
      {
        number: 6,
        text: "as to zeal, a persecutor of the church; as to the righteousness which is in the Law, found blameless.",
        keywords: ["righteousness", "church"],
      },
      {
        number: 7,
        text: "But whatever things were gain to me, these things I have counted as loss because of Christ.",
        keywords: ["Christ", "whatever"],
      },
      {
        number: 8,
        text: "More than that, I count all things to be loss in view of the surpassing value of knowing Christ Jesus my Lord, for whom I have suffered the loss of all things, and count them mere rubbish, so that I may gain Christ,",
        keywords: ["Christ", "Jesus", "Lord", "surpassing", "knowing"],
      },
      {
        number: 9,
        text: "and may be found in Him, not having a righteousness of my own derived from the Law, but that which is through faith in Christ, the righteousness which comes from God on the basis of faith,",
        keywords: ["Christ", "righteousness", "God"],
      },
      {
        number: 10,
        text: "that I may know Him and the power of His resurrection and the fellowship of His sufferings, being conformed to His death;",
        keywords: ["resurrection", "death"],
      },
      {
        number: 11,
        text: "if somehow I may attain to the resurrection from the dead.",
        keywords: ["resurrection"],
      },
      {
        number: 12,
        text: "Not that I have already grasped it all or have already become perfect, but I press on if I may also take hold of that for which I was even taken hold of by Christ Jesus.",
        keywords: ["Christ", "Jesus", "already"],
      },
      {
        number: 13,
        text: "Brothers and sisters, I do not regard myself as having taken hold of it yet; but one thing I do: forgetting what lies behind and reaching forward to what lies ahead,",
        keywords: ["Brothers", "sisters", "forgetting", "reaching"],
      },
      {
        number: 14,
        text: "I press on toward the goal for the prize of the upward call of God in Christ Jesus.",
        keywords: ["Christ", "Jesus"],
      },
      {
        number: 15,
        text: "Therefore, all who are mature, let’s have this attitude; and if in anything you have a different attitude, God will reveal that to you as well;",
        keywords: ["God", "attitude", "anything"],
      },
      {
        number: 16,
        text: "however, let’s keep living by that same standard to which we have attained.",
        keywords: ["standard", "attained"],
      },
      {
        number: 17,
        text: "Brothers and sisters, join in following my example, and observe those who walk according to the pattern you have in us.",
        keywords: ["Brothers", "sisters"],
      },
      {
        number: 18,
        text: "For many walk, of whom I often told you, and now tell you even as I weep, that they are the enemies of the cross of Christ,",
        keywords: ["Christ", "cross"],
      },
      {
        number: 19,
        text: "whose end is destruction, whose god is their appetite, and whose glory is in their shame, who have their minds on earthly things.",
        keywords: ["glory", "god", "destruction"],
      },
      {
        number: 20,
        text: "For our citizenship is in heaven, from which we also eagerly wait for a Savior, the Lord Jesus Christ;",
        keywords: ["Jesus", "Christ"],
      },
      {
        number: 21,
        text: "who will transform the body of our lowly condition into conformity with His glorious body, by the exertion of the power that He has even to subject all things to Himself.",
        keywords: ["transform", "condition", "conformity"],
      },
    ],
  },
  {
    slug: "philippians-4",
    book: "Philippians",
    chapter: 4,
    reference: "Philippians 4",
    verses: [
      {
        number: 1,
        text: "Therefore, my beloved brothers and sisters, whom I long to see, my joy and crown, stand firm in the Lord in this way, my beloved.",
        keywords: ["Lord", "beloved", "brothers"],
      },
      {
        number: 2,
        text: "I urge Euodia and I urge Syntyche to live in harmony in the Lord.",
        keywords: ["Lord", "Syntyche"],
      },
      {
        number: 3,
        text: "Indeed, true companion, I ask you also, help these women who have shared my struggle in the cause of the gospel, together with Clement as well as the rest of my fellow workers, whose names are in the book of life.",
        keywords: ["gospel", "life", "Clement", "companion", "struggle"],
      },
      {
        number: 4,
        text: "Rejoice in the Lord always; again I will say, rejoice!",
        keywords: ["Lord"],
      },
      {
        number: 5,
        text: "Let your gentle spirit be known to all people. The Lord is near.",
        keywords: ["Lord", "spirit"],
      },
      {
        number: 6,
        text: "Do not be anxious about anything, but in everything by prayer and pleading with thanksgiving let your requests be made known to God.",
        keywords: ["God", "anxious", "anything"],
      },
      {
        number: 7,
        text: "And the peace of God, which surpasses all comprehension, will guard your hearts and minds in Christ Jesus.",
        keywords: ["Christ", "Jesus", "God"],
      },
      {
        number: 8,
        text: "Finally, brothers and sisters, whatever is true, whatever is honorable, whatever is right, whatever is pure, whatever is lovely, whatever is commendable, if there is any excellence and if anything worthy of praise, think about these things.",
        keywords: ["Finally", "brothers", "sisters", "whatever", "honorable", "commendable"],
      },
      {
        number: 9,
        text: "As for the things you have learned and received and heard and seen in me, practice these things, and the God of peace will be with you.",
        keywords: ["God", "peace", "learned"],
      },
      {
        number: 10,
        text: "But I rejoiced in the Lord greatly, that now at last you have revived your concern for me; indeed, you were concerned before, but you lacked an opportunity to act.",
        keywords: ["Lord", "rejoiced", "greatly"],
      },
      {
        number: 11,
        text: "Not that I speak from need, for I have learned to be content in whatever circumstances I am.",
        keywords: ["learned", "content"],
      },
      {
        number: 12,
        text: "I know how to get along with little, and I also know how to live in prosperity; in any and every circumstance I have learned the secret of being filled and going hungry, both of having abundance and suffering need.",
        keywords: ["prosperity", "circumstance", "learned", "abundance"],
      },
      {
        number: 13,
        text: "I can do all things through Him who strengthens me.",
        keywords: ["strengthens"],
      },
      {
        number: 14,
        text: "Nevertheless, you have done well to share with me in my difficulty.",
        keywords: ["Nevertheless"],
      },
      {
        number: 15,
        text: "You yourselves also know, Philippians, that at the first preaching of the gospel, after I left Macedonia, no church shared with me in the matter of giving and receiving except you alone;",
        keywords: ["gospel", "church", "Philippians", "Macedonia"],
      },
      {
        number: 16,
        text: "for even in Thessalonica you sent a gift more than once for my needs.",
        keywords: ["Thessalonica"],
      },
      {
        number: 17,
        text: "Not that I seek the gift itself, but I seek the profit which increases to your account.",
        keywords: ["increases", "account"],
      },
      {
        number: 18,
        text: "But I have received everything in full and have an abundance; I am amply supplied, having received from Epaphroditus what you have sent, a fragrant aroma, an acceptable sacrifice, pleasing to God.",
        keywords: ["God", "Epaphroditus", "received", "everything"],
      },
      {
        number: 19,
        text: "And my God will supply all your needs according to His riches in glory in Christ Jesus.",
        keywords: ["Christ", "Jesus"],
      },
      {
        number: 20,
        text: "Now to our God and Father be the glory forever and ever. Amen.",
        keywords: ["Father"],
      },
      {
        number: 21,
        text: "Greet every saint in Christ Jesus. The brothers who are with me greet you.",
        keywords: ["Christ", "Jesus"],
      },
      {
        number: 22,
        text: "All the saints greet you, especially those of Caesar’s household.",
        keywords: ["Caesars"],
      },
      {
        number: 23,
        text: "The grace of the Lord Jesus Christ be with your spirit.",
        keywords: ["Jesus"],
      },
    ],
  },
  {
    slug: "colossians-1",
    book: "Colossians",
    chapter: 1,
    reference: "Colossians 1",
    verses: [
      {
        number: 1,
        text: "Paul, an apostle of Christ Jesus by the will of God, and Timothy our brother,",
        keywords: ["Christ", "Jesus"],
      },
      {
        number: 2,
        text: "To the saints and faithful brothers and sisters in Christ who are at Colossae: Grace to you and peace from God our Father.",
        keywords: ["Christ", "Grace", "Father"],
      },
      {
        number: 3,
        text: "We give thanks to God, the Father of our Lord Jesus Christ, praying always for you,",
        keywords: ["Father", "Jesus"],
      },
      {
        number: 4,
        text: "since we heard of your faith in Christ Jesus and the love which you have for all the saints;",
        keywords: ["Christ", "Jesus"],
      },
      {
        number: 5,
        text: "because of the hope reserved for you in heaven, of which you previously heard in the word of truth, the gospel",
        keywords: ["gospel", "hope"],
      },
      {
        number: 6,
        text: "which has come to you, just as in all the world also it is bearing fruit and increasing, even as it has been doing in you also since the day you heard it and understood the grace of God in truth;",
        keywords: ["God", "grace", "bearing"],
      },
      {
        number: 7,
        text: "just as you learned it from Epaphras, our beloved fellow bond-servant, who is a faithful servant of Christ on our behalf,",
        keywords: ["Christ", "Epaphras", "learned"],
      },
      {
        number: 8,
        text: "and he also informed us of your love in the Spirit.",
        keywords: ["Spirit"],
      },
      {
        number: 9,
        text: "For this reason we also, since the day we heard about it, have not ceased praying for you and asking that you may be filled with the knowledge of His will in all spiritual wisdom and understanding,",
        keywords: ["praying", "knowledge", "spiritual"],
      },
      {
        number: 10,
        text: "so that you will walk in a manner worthy of the Lord, to please Him in all respects, bearing fruit in every good work and increasing in the knowledge of God;",
        keywords: ["Lord", "God", "respects", "bearing"],
      },
      {
        number: 11,
        text: "strengthened with all power, according to His glorious might, for the attaining of all perseverance and patience; joyously",
        keywords: ["strengthened", "glorious"],
      },
      {
        number: 12,
        text: "giving thanks to the Father, who has qualified you to share in the inheritance of the saints in light.",
        keywords: ["Father", "qualified"],
      },
      {
        number: 13,
        text: "For He rescued us from the domain of darkness, and transferred us to the kingdom of His beloved Son,",
        keywords: ["kingdom", "Son"],
      },
      {
        number: 14,
        text: "in whom we have redemption, the forgiveness of sins.",
        keywords: ["sins"],
      },
      {
        number: 15,
        text: "He is the image of the invisible God, the firstborn of all creation:",
        keywords: ["God"],
      },
      {
        number: 16,
        text: "for by Him all things were created, both in the heavens and on earth, visible and invisible, whether thrones, or dominions, or rulers, or authorities—all things have been created through Him and for Him.",
        keywords: ["created", "heavens", "visible", "invisible"],
      },
      {
        number: 17,
        text: "He is before all things, and in Him all things hold together.",
        keywords: ["together"],
      },
      {
        number: 18,
        text: "He is also the head of the body, the church; and He is the beginning, the firstborn from the dead, so that He Himself will come to have first place in everything.",
        keywords: ["church", "beginning", "firstborn"],
      },
      {
        number: 19,
        text: "For it was the Father’s good pleasure for all the fullness to dwell in Him,",
        keywords: ["Fathers"],
      },
      {
        number: 20,
        text: "and through Him to reconcile all things to Himself, whether things on earth or things in heaven, having made peace through the blood of His cross.",
        keywords: ["peace", "cross", "reconcile"],
      },
      {
        number: 21,
        text: "And although you were previously alienated and hostile in attitude, engaged in evil deeds,",
        keywords: ["previously", "alienated"],
      },
      {
        number: 22,
        text: "yet He has now reconciled you in His body of flesh through death, in order to present you before Him holy and blameless and beyond reproach—",
        keywords: ["death", "holy", "reconciled"],
      },
      {
        number: 23,
        text: "if indeed you continue in the faith firmly established and steadfast, and not shifting from the hope of the gospel that you have heard, which was proclaimed in all creation under heaven, and of which I, Paul, was made a minister.",
        keywords: ["faith", "gospel", "hope", "continue"],
      },
      {
        number: 24,
        text: "Now I rejoice in my sufferings for your sake, and in my flesh I am supplementing what is lacking in Christ’s afflictions in behalf of His body, which is the church.",
        keywords: ["church", "Christs", "rejoice"],
      },
      {
        number: 25,
        text: "I was made a minister of this church according to the commission from God granted to me for your benefit, so that I might fully carry out the preaching of the word of God,",
        keywords: ["God", "church", "minister"],
      },
      {
        number: 26,
        text: "that is, the mystery which had been hidden from the past ages and generations, but now has been revealed to His saints,",
        keywords: ["mystery", "generations"],
      },
      {
        number: 27,
        text: "to whom God willed to make known what the wealth of the glory of this mystery among the Gentiles is, the mystery that is Christ in you, the hope of glory.",
        keywords: ["Christ", "God", "mystery"],
      },
      {
        number: 28,
        text: "We proclaim Him, admonishing every person and teaching every person with all wisdom, so that we may present every person complete in Christ.",
        keywords: ["Christ", "proclaim", "admonishing"],
      },
      {
        number: 29,
        text: "For this purpose I also labor, striving according to His power which works mightily within me.",
        keywords: ["purpose", "striving"],
      },
    ],
  },
  {
    slug: "colossians-2",
    book: "Colossians",
    chapter: 2,
    reference: "Colossians 2",
    verses: [
      {
        number: 1,
        text: "For I want you to know how great a struggle I have in your behalf and for those who are at Laodicea, and for all those who have not personally seen my face,",
        keywords: ["Laodicea", "struggle", "personally"],
      },
      {
        number: 2,
        text: "that their hearts may be encouraged, having been knit together in love, and that they would attain to all the wealth that comes from the full assurance of understanding, resulting in a true knowledge of God’s mystery, that is, Christ Himself,",
        keywords: ["Christ", "mystery", "love", "encouraged", "together"],
      },
      {
        number: 3,
        text: "in whom are hidden all the treasures of wisdom and knowledge.",
        keywords: ["treasures"],
      },
      {
        number: 4,
        text: "I say this so that no one will deceive you with persuasive arguments.",
        keywords: ["deceive"],
      },
      {
        number: 5,
        text: "For even though I am absent in body, I am nevertheless with you in spirit, rejoicing to see your orderly manner and the stability of your faith in Christ.",
        keywords: ["Christ", "spirit", "faith"],
      },
      {
        number: 6,
        text: "Therefore, as you have received Christ Jesus the Lord, so walk in Him,",
        keywords: ["Christ"],
      },
      {
        number: 7,
        text: "having been firmly rooted and now being built up in Him and established in your faith, just as you were instructed, and overflowing with gratitude.",
        keywords: ["faith", "established"],
      },
      {
        number: 8,
        text: "See to it that there is no one who takes you captive through philosophy and empty deception in accordance with human tradition, in accordance with the elementary principles of the world, rather than in accordance with Christ.",
        keywords: ["Christ", "See", "captive", "philosophy"],
      },
      {
        number: 9,
        text: "For in Him all the fullness of Deity dwells in bodily form,",
        keywords: ["Deity"],
      },
      {
        number: 10,
        text: "and in Him you have been made complete, and He is the head over every ruler and authority;",
        keywords: ["complete"],
      },
      {
        number: 11,
        text: "and in Him you were also circumcised with a circumcision performed without hands, in the removal of the body of the flesh by the circumcision of Christ,",
        keywords: ["Christ", "circumcised", "circumcision"],
      },
      {
        number: 12,
        text: "having been buried with Him in baptism, in which you were also raised with Him through faith in the working of God, who raised Him from the dead.",
        keywords: ["God", "faith"],
      },
      {
        number: 13,
        text: "And when you were dead in your wrongdoings and the uncircumcision of your flesh, He made you alive together with Him, having forgiven us all our wrongdoings,",
        keywords: ["wrongdoings", "uncircumcision", "together"],
      },
      {
        number: 14,
        text: "having canceled the certificate of debt consisting of decrees against us, which was hostile to us; and He has taken it out of the way, having nailed it to the cross.",
        keywords: ["cross", "canceled", "certificate"],
      },
      {
        number: 15,
        text: "When He had disarmed the rulers and authorities, He made a public display of them, having triumphed over them through Him.",
        keywords: ["disarmed", "authorities"],
      },
      {
        number: 16,
        text: "Therefore, no one is to act as your judge in regard to food and drink, or in respect to a festival or a new moon, or a Sabbath day—",
        keywords: ["Sabbath", "respect", "festival"],
      },
      {
        number: 17,
        text: "things which are only a shadow of what is to come; but the substance belongs to Christ.",
        keywords: ["Christ", "substance"],
      },
      {
        number: 18,
        text: "Take care that no one keeps defrauding you of your prize by delighting in humility and the worship of the angels, taking his stand on visions he has seen, inflated without cause by his fleshly mind,",
        keywords: ["Take", "defrauding", "delighting", "humility", "worship"],
      },
      {
        number: 19,
        text: "and not holding firmly to the head, from whom the entire body, being supplied and held together by the joints and ligaments, grows with a growth which is from God.",
        keywords: ["God", "holding", "supplied", "together"],
      },
      {
        number: 20,
        text: "If you have died with Christ to the elementary principles of the world, why, as if you were living in the world, do you submit yourself to decrees, such as,",
        keywords: ["Christ", "elementary", "principles"],
      },
      {
        number: 21,
        text: "“Do not handle, do not taste, do not touch!”",
        keywords: ["handle"],
      },
      {
        number: 22,
        text: "(which all refer to things destined to perish with use)—in accordance with the commandments and teachings of man?",
        keywords: ["destined", "accordance", "commandments"],
      },
      {
        number: 23,
        text: "These are matters which do have the appearance of wisdom in self-made religion and humility and severe treatment of the body, but are of no value against fleshly indulgence.",
        keywords: ["matters", "appearance", "selfmade"],
      },
    ],
  },
  {
    slug: "colossians-3",
    book: "Colossians",
    chapter: 3,
    reference: "Colossians 3",
    verses: [
      {
        number: 1,
        text: "Therefore, if you have been raised with Christ, keep seeking the things that are above, where Christ is, seated at the right hand of God.",
        keywords: ["Christ", "God", "seeking"],
      },
      {
        number: 2,
        text: "Set your minds on the things that are above, not on the things that are on earth.",
        keywords: ["Set"],
      },
      {
        number: 3,
        text: "For you have died, and your life is hidden with Christ in God.",
        keywords: ["Christ"],
      },
      {
        number: 4,
        text: "When Christ, who is our life, is revealed, then you also will be revealed with Him in glory.",
        keywords: ["Christ"],
      },
      {
        number: 5,
        text: "Therefore, treat the parts of your earthly body as dead to sexual immorality, impurity, passion, evil desire, and greed, which amounts to idolatry.",
        keywords: ["earthly", "immorality", "impurity", "passion"],
      },
      {
        number: 6,
        text: "For it is because of these things that the wrath of God is coming upon the sons of disobedience,",
        keywords: ["God", "disobedience"],
      },
      {
        number: 7,
        text: "and in them you also once walked, when you were living in them.",
        keywords: ["walked"],
      },
      {
        number: 8,
        text: "But now you also, rid yourselves of all of them: anger, wrath, malice, slander, and obscene speech from your mouth.",
        keywords: ["slander", "obscene"],
      },
      {
        number: 9,
        text: "Do not lie to one another, since you stripped off the old self with its evil practices,",
        keywords: ["stripped", "practices"],
      },
      {
        number: 10,
        text: "and have put on the new self, which is being renewed to a true knowledge according to the image of the One who created it—",
        keywords: ["renewed", "knowledge"],
      },
      {
        number: 11,
        text: "a renewal in which there is no distinction between Greek and Jew, circumcised and uncircumcised, barbarian, Scythian, slave, and free, but Christ is all, and in all.",
        keywords: ["Christ", "Scythian", "Greek"],
      },
      {
        number: 12,
        text: "So, as those who have been chosen of God, holy and beloved, put on a heart of compassion, kindness, humility, gentleness, and patience;",
        keywords: ["God", "holy", "beloved"],
      },
      {
        number: 13,
        text: "bearing with one another, and forgiving each other, whoever has a complaint against anyone; just as the Lord forgave you, so must you do also.",
        keywords: ["Lord", "bearing"],
      },
      {
        number: 14,
        text: "In addition to all these things put on love, which is the perfect bond of unity.",
        keywords: ["love", "addition"],
      },
      {
        number: 15,
        text: "Let the peace of Christ, to which you were indeed called in one body, rule in your hearts; and be thankful.",
        keywords: ["Christ", "peace"],
      },
      {
        number: 16,
        text: "Let the word of Christ richly dwell within you, with all wisdom teaching and admonishing one another with psalms, hymns, and spiritual songs, singing with thankfulness in your hearts to God.",
        keywords: ["Christ", "God", "Let", "teaching"],
      },
      {
        number: 17,
        text: "Whatever you do in word or deed, do everything in the name of the Lord Jesus, giving thanks through Him to God the Father.",
        keywords: ["Jesus", "Father", "Lord"],
      },
      {
        number: 18,
        text: "Wives, be subject to your husbands, as is fitting in the Lord.",
        keywords: ["Lord"],
      },
      {
        number: 19,
        text: "Husbands, love your wives and do not become bitter against them.",
        keywords: ["love"],
      },
      {
        number: 20,
        text: "Children, obey your parents in everything, for this is pleasing to the Lord.",
        keywords: ["Lord", "Children"],
      },
      {
        number: 21,
        text: "Fathers, do not antagonize your children, so that they will not become discouraged.",
        keywords: ["Fathers"],
      },
      {
        number: 22,
        text: "Slaves, obey those who are your human masters in everything, not with eye-service, as people-pleasers, but with sincerity of heart, fearing the Lord.",
        keywords: ["Lord", "Slaves", "masters"],
      },
      {
        number: 23,
        text: "Whatever you do, do your work heartily, as for the Lord and not for people,",
        keywords: ["Lord"],
      },
      {
        number: 24,
        text: "knowing that it is from the Lord that you will receive the reward of the inheritance. It is the Lord Christ whom you serve.",
        keywords: ["Christ", "Lord"],
      },
      {
        number: 25,
        text: "For the one who does wrong will receive the consequences of the wrong which he has done, and that without partiality.",
        keywords: ["receive", "consequences"],
      },
    ],
  },
  {
    slug: "colossians-4",
    book: "Colossians",
    chapter: 4,
    reference: "Colossians 4",
    verses: [
      {
        number: 1,
        text: "Masters, grant your slaves justice and fairness, knowing that you also have a Master in heaven.",
        keywords: ["Masters", "Master"],
      },
      {
        number: 2,
        text: "Devote yourselves to prayer, keeping alert in it with an attitude of thanksgiving;",
        keywords: ["Devote", "keeping"],
      },
      {
        number: 3,
        text: "praying at the same time for us as well, that God will open up to us a door for the word, so that we may proclaim the mystery of Christ, for which I have also been imprisoned;",
        keywords: ["Christ", "God", "mystery"],
      },
      {
        number: 4,
        text: "that I may make it clear in the way that I ought to proclaim it.",
        keywords: ["proclaim"],
      },
      {
        number: 5,
        text: "Conduct yourselves with wisdom toward outsiders, making the most of the opportunity.",
        keywords: ["Conduct"],
      },
      {
        number: 6,
        text: "Your speech must always be with grace, as though seasoned with salt, so that you will know how you should respond to each person.",
        keywords: ["grace", "seasoned"],
      },
      {
        number: 7,
        text: "As to all my affairs, Tychicus, our beloved brother and faithful servant and fellow bond-servant in the Lord, will bring you information.",
        keywords: ["Lord", "Tychicus", "affairs"],
      },
      {
        number: 8,
        text: "For I have sent him to you for this very purpose, that you may know about our circumstances and that he may encourage your hearts;",
        keywords: ["purpose", "circumstances"],
      },
      {
        number: 9,
        text: "and with him is Onesimus, our faithful and beloved brother, who is one of your own. They will inform you about the whole situation here.",
        keywords: ["Onesimus", "faithful"],
      },
      {
        number: 10,
        text: "Aristarchus, my fellow prisoner, sends you his greetings; and also Barnabas’ cousin Mark (about whom you received instructions; if he comes to you, welcome him);",
        keywords: ["Aristarchus", "Barnabas", "prisoner"],
      },
      {
        number: 11,
        text: "and also Jesus who is called Justus; these are the only fellow workers for the kingdom of God who are from the circumcision, and they have proved to be an encouragement to me.",
        keywords: ["Jesus", "kingdom", "God"],
      },
      {
        number: 12,
        text: "Epaphras, who is one of your own, a bond-servant of Christ Jesus, sends you his greetings, always striving earnestly for you in his prayers, that you may stand mature and fully assured in all the will of God.",
        keywords: ["Christ", "Jesus", "God", "Epaphras"],
      },
      {
        number: 13,
        text: "For I testify for him that he has a deep concern for you and for those who are in Laodicea and Hierapolis.",
        keywords: ["Laodicea"],
      },
      {
        number: 14,
        text: "Luke, the beloved physician, sends you his greetings, and Demas does also.",
        keywords: ["Demas", "Luke"],
      },
      {
        number: 15,
        text: "Greet the brothers and sisters who are in Laodicea and also Nympha and the church that is in her house.",
        keywords: ["church", "Laodicea"],
      },
      {
        number: 16,
        text: "When this letter is read among you, have it also read in the church of the Laodiceans; and you, for your part, read my letter that is coming from Laodicea.",
        keywords: ["church", "Laodiceans", "Laodicea"],
      },
      {
        number: 17,
        text: "Tell Archippus, “See to the ministry which you have received in the Lord, so that you may fulfill it.”",
        keywords: ["Lord", "Archippus"],
      },
      {
        number: 18,
        text: "I, Paul, write this greeting with my own hand. Remember my imprisonment. Grace be with you.",
        keywords: ["Grace", "Remember"],
      },
    ],
  },
];

export function getChapter(slug: string): Chapter | undefined {
  return chapters.find((c) => c.slug === slug);
}
